---
sudo: false
language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-django111
    - python: 3.4
      env: TOXENV=py34-django111
    - python: 3.4
      env: TOXENV=py34-django20
    - python: 3.5
      env: TOXENV=py35-django111
    - python: 3.5
      env: TOXENV=py35-django20
    - python: 3.5
      env: TOXENV=py35-django21
    - python: 3.5
      env: TOXENV=py35-django22
      dist: xenial
      sudo: true
    - python: 3.6
      env: TOXENV=py36-django111
    - python: 3.6
      env: TOXENV=py36-django20
    - python: 3.6
      env: TOXENV=py36-django21
    - python: 3.6
      env: TOXENV=py36-django22
      dist: xenial
      sudo: true
    - python: 3.7
      env: TOXENV=py37-django111
      dist: xenial
      sudo: true
    - python: 3.7
      env: TOXENV=py37-django20
      dist: xenial
      sudo: true
    - python: 3.7
      env: TOXENV=py37-django21
      dist: xenial
      sudo: true
    - python: 3.7
      env: TOXENV=py37-django22
      dist: xenial
      sudo: true

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip

deps:
  - codecov

install:
  - pip install tox codecov

script:
  - tox -e $TOXENV

after_success:
  - tox -e coverage-report
  - codecov

notifications:
  email: false
