---
sudo: false
language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-django22
      dist: xenial
      sudo: true
    - python: 3.6
      env: TOXENV=py36-django22
      dist: xenial
      sudo: true
    - python: 3.6
      env: TOXENV=py36-django30
      dist: xenial
      sudo: true
    - python: 3.7
      env: TOXENV=py37-django22
      dist: xenial
      sudo: true
    - python: 3.7
      env: TOXENV=py37-django30
      dist: xenial
      sudo: true
    - python: 3.8
      env: TOXENV=py38-django22
      dist: xenial
      sudo: true
    - python: 3.8
      env: TOXENV=py38-django30
      dist: xenial
      sudo: true

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip

deps:
  - codecov

install:
  - pip install tox codecov

script:
  - tox -e $TOXENV

after_success:
  - tox -e coverage-report
  - codecov

notifications:
  email: false
